# Generated by Django 4.0.6 on 2022-08-02 08:08

import count.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=count.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['zip', 'txt'], 'Uploaded File Is Not Zipped!')]),
        ),
    ]
