# Generated by Django 4.0.6 on 2022-08-02 08:14

import count.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=count.models.user_directory_path),
        ),
    ]
