# Generated by Django 4.0.6 on 2022-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='successful',
        ),
        migrations.AddField(
            model_name='status',
            name='date_done',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='task_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
