# Generated by Django 4.0.6 on 2022-09-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('count', '0003_remove_status_successful_status_date_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult'),
        ),
    ]
