# Generated by Django 4.0.6 on 2022-08-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0004_alter_category_user_alter_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='root',
        ),
        migrations.RemoveField(
            model_name='file',
            name='root',
        ),
    ]
