# Generated by Django 4.0.6 on 2022-08-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0005_remove_category_root_remove_file_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
