# Generated by Django 4.0.6 on 2022-08-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0006_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='father',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='count.category'),
        ),
    ]
