# Generated by Django 4.0.6 on 2022-08-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0007_alter_category_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='count.category'),
        ),
    ]
